# frozen_string_literal: true

source 'https://rubygems.org'
gem 'benchmark'
gem 'berkshelf'
gem 'cookstyle'
gem 'csv'
gem 'highline'
gem 'inspec', '>= 6.6.0'
gem 'inspec-bin'
gem 'inspec-core'
gem 'kitchen-ansible'
gem 'kitchen-docker'
gem 'kitchen-ec2'
gem 'kitchen-inspec'
gem 'kitchen-oci'
gem 'kitchen-sync'
gem 'parser', '3.3.0.5'
gem 'pry-byebug'
gem 'rake'
gem 'rubocop'
gem 'rubocop-rake'
gem 'syslog'
gem 'test-kitchen'
gem 'train-awsssm'
